sudo: required

language: java

jdk:
- openjdk8
- oraclejdk9

before_install:
- sudo apt-get update -q

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3   # Give xvfb some time to start

notifications:
  irc:
    channels:
      - "chat.freenode.net#gral"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"

after_success:
- gradle cobertura coveralls
